pipeline {
  agent any
  stages {
    stage('Build Solution') {
      steps {
        bat """
        set MSB="C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\MSBuild\\Current\\Bin\\amd64\\MSBuild.exe"
        %MSB% AtServerEngine\\T_Survivor.sln -t:Rebuild -p:Configuration=Release -p:Platform=x64
        """
      }
    }
  }
}