pipeline {
  agent any

  stages {
    stage('Clean and Rebuild Solution') {
      steps {
        bat """
        set MSB="C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\MSBuild\\Current\\Bin\\amd64\\MSBuild.exe"

        rem --- Clean 먼저 실행 ---
        %MSB% AtServerEngine\\T_Survivor.sln -t:Clean -p:Configuration=Release -p:Platform=x64

        rem --- 다시 빌드(Rebuild) ---
        %MSB% AtServerEngine\\T_Survivor.sln -t:Rebuild -p:Configuration=Release -p:Platform=x64
        """
      }
    }
  }
}