pipeline {
  agent any

  stages {
    stage('Build Projects') {
      steps {
        bat """
        set MSB="C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\MSBuild\\Current\\Bin\\amd64\\MSBuild.exe"

        %MSB% AtServerEngine\\ServerCore\\ServerCore.vcxproj -p:Configuration=Release -p:Platform=x64
        """
      }
    }
  }
}