// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Enum.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Protocol {

  /// <summary>Holder for reflection information generated from Enum.proto</summary>
  public static partial class EnumReflection {

    #region Descriptor
    /// <summary>File descriptor for Enum.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EnumReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgpFbnVtLnByb3RvEghQcm90b2NvbCpcCgtFUmVzdWx0Q29kZRIXChNSRVNV",
            "TFRfQ09ERV9TVUNDRVNTEAASHwobUkVTVUxUX0NPREVfRkFJTF9ST09NX0VO",
            "VEVSEAESEwoPUkVTVUxUX0NPREVfTUFYEAIqgAEKC0VPYmplY3RUeXBlEhQK",
            "EE9CSkVDVF9UWVBFX05PTkUQABIVChFPQkpFQ1RfVFlQRV9BQ1RPUhABEhoK",
            "Fk9CSkVDVF9UWVBFX1BST0pFQ1RJTEUQAhITCg9PQkpFQ1RfVFlQRV9FTlYQ",
            "AxITCg9PQkpFQ1RfVFlQRV9NQVgQBCp4CgpFQWN0b3JUeXBlEhMKD0FDVE9S",
            "X1RZUEVfTk9ORRAAEhUKEUFDVE9SX1RZUEVfUExBWUVSEAESFgoSQUNUT1Jf",
            "VFlQRV9NT05TVEVSEAISEgoOQUNUT1JfVFlQRV9OUEMQAxISCg5BQ1RPUl9U",
            "WVBFX01BWBAEKm8KCEVCYWdUeXBlEhEKDUJBR19UWVBFX05PTkUQABIWChJC",
            "QUdfVFlQRV9FUVVJUE1FTlQQARIQCgxCQUdfVFlQRV9FVEMQAhIUChBCQUdf",
            "VFlQRV9VU0VBQkxFEAMSEAoMQkFHX1RZUEVfTUFYEAQqfgoLRVBsYXllclR5",
            "cGUSFAoQUExBWUVSX1RZUEVfTk9ORRAAEhYKElBMQVlFUl9UWVBFX0tOSUdI",
            "VBABEhQKEFBMQVlFUl9UWVBFX01BR0UQAhIWChJQTEFZRVJfVFlQRV9BUkNI",
            "RVIQAxITCg9QTEFZRVJfVFlQRV9NQVgQBCp1CgpFTW92ZVN0YXRlEhMKD01P",
            "VkVfU1RBVEVfTk9ORRAAEhMKD01PVkVfU1RBVEVfSURMRRABEhIKDk1PVkVf",
            "U1RBVEVfUlVOEAISEwoPTU9WRV9TVEFURV9KVU1QEAMSFAoQTU9WRV9TVEFU",
            "RV9TS0lMTBAEKu0BCg5FRXF1aXBTbG90VHlwZRIYChRFUVVJUF9TTE9UX1RZ",
            "UEVfTk9ORRAAEhoKFkVRVUlQX1NMT1RfVFlQRV9XRUFQT04QARIeChpFUVVJ",
            "UF9TTE9UX1RZUEVfU1VCX1dFQVBPThACEhoKFkVRVUlQX1NMT1RfVFlQRV9I",
            "RUxNQVQQAxIZChVFUVVJUF9TTE9UX1RZUEVfQVJNT1IQBBIaChZFUVVJUF9T",
            "TE9UX1RZUEVfR0xPVkVTEAUSGQoVRVFVSVBfU0xPVF9UWVBFX0JPT1RTEAYS",
            "FwoTRVFVSVBfU0xPVF9UWVBFX01BWBAHKooBCgVFU3RhdBINCglTVEFUX05P",
            "TkUQABIRCg1TVEFUX1NUUkVOR1RIEAESCwoHU1RBVF9IUBACEgsKB1NUQVRf",
            "TVAQAxIQCgxTVEFUX0RFRkVOU0UQBBIOCgpTVEFUX1NQRUVEEAUSFQoRU1RB",
            "VF9JTlRFTExJR0VOQ0UQBhIMCghTVEFUX01BWBAHKmcKE0VBbmltYXRpb25Q",
            "YXJhbVR5cGUSGAoUQU5JTV9QQVJBTV9UWVBFX0JPT0wQABIZChVBTklNX1BB",
            "UkFNX1RZUEVfRkxPQVQQARIbChdBTklNX1BBUkFNX1RZUEVfVFJJR0dFUhAC",
            "KmIKCkVSb29tU3RhdGUSEwoPUk9PTV9TVEFURV9OT05FEAASFgoSUk9PTV9T",
            "VEFURV9XQUlUSU5HEAESEwoPUk9PTV9TVEFURV9QTEFZEAISEgoOUk9PTV9T",
            "VEFURV9NQVgQA0ILqgIIUHJvdG9jb2xiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Protocol.EResultCode), typeof(global::Protocol.EObjectType), typeof(global::Protocol.EActorType), typeof(global::Protocol.EBagType), typeof(global::Protocol.EPlayerType), typeof(global::Protocol.EMoveState), typeof(global::Protocol.EEquipSlotType), typeof(global::Protocol.EStat), typeof(global::Protocol.EAnimationParamType), typeof(global::Protocol.ERoomState), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum EResultCode {
    /// <summary>
    /// 성공
    /// </summary>
    [pbr::OriginalName("RESULT_CODE_SUCCESS")] ResultCodeSuccess = 0,
    /// <summary>
    /// 룸 입장 실패
    /// </summary>
    [pbr::OriginalName("RESULT_CODE_FAIL_ROOM_ENTER")] ResultCodeFailRoomEnter = 1,
    [pbr::OriginalName("RESULT_CODE_MAX")] ResultCodeMax = 2,
  }

  public enum EObjectType {
    [pbr::OriginalName("OBJECT_TYPE_NONE")] ObjectTypeNone = 0,
    /// <summary>
    /// 엑터
    /// </summary>
    [pbr::OriginalName("OBJECT_TYPE_ACTOR")] ObjectTypeActor = 1,
    /// <summary>
    /// 발사체
    /// </summary>
    [pbr::OriginalName("OBJECT_TYPE_PROJECTILE")] ObjectTypeProjectile = 2,
    /// <summary>
    /// 환경 오브젝트
    /// </summary>
    [pbr::OriginalName("OBJECT_TYPE_ENV")] ObjectTypeEnv = 3,
    [pbr::OriginalName("OBJECT_TYPE_MAX")] ObjectTypeMax = 4,
  }

  public enum EActorType {
    [pbr::OriginalName("ACTOR_TYPE_NONE")] ActorTypeNone = 0,
    /// <summary>
    /// 플레이어
    /// </summary>
    [pbr::OriginalName("ACTOR_TYPE_PLAYER")] ActorTypePlayer = 1,
    /// <summary>
    /// 몬스터
    /// </summary>
    [pbr::OriginalName("ACTOR_TYPE_MONSTER")] ActorTypeMonster = 2,
    /// <summary>
    /// NPC
    /// </summary>
    [pbr::OriginalName("ACTOR_TYPE_NPC")] ActorTypeNpc = 3,
    [pbr::OriginalName("ACTOR_TYPE_MAX")] ActorTypeMax = 4,
  }

  public enum EBagType {
    [pbr::OriginalName("BAG_TYPE_NONE")] BagTypeNone = 0,
    /// <summary>
    /// 장비
    /// </summary>
    [pbr::OriginalName("BAG_TYPE_EQUIPMENT")] BagTypeEquipment = 1,
    /// <summary>
    /// 기타
    /// </summary>
    [pbr::OriginalName("BAG_TYPE_ETC")] BagTypeEtc = 2,
    /// <summary>
    /// 사용품
    /// </summary>
    [pbr::OriginalName("BAG_TYPE_USEABLE")] BagTypeUseable = 3,
    [pbr::OriginalName("BAG_TYPE_MAX")] BagTypeMax = 4,
  }

  public enum EPlayerType {
    [pbr::OriginalName("PLAYER_TYPE_NONE")] PlayerTypeNone = 0,
    /// <summary>
    /// 기사
    /// </summary>
    [pbr::OriginalName("PLAYER_TYPE_KNIGHT")] PlayerTypeKnight = 1,
    /// <summary>
    /// 마법사
    /// </summary>
    [pbr::OriginalName("PLAYER_TYPE_MAGE")] PlayerTypeMage = 2,
    /// <summary>
    /// 궁수
    /// </summary>
    [pbr::OriginalName("PLAYER_TYPE_ARCHER")] PlayerTypeArcher = 3,
    [pbr::OriginalName("PLAYER_TYPE_MAX")] PlayerTypeMax = 4,
  }

  public enum EMoveState {
    [pbr::OriginalName("MOVE_STATE_NONE")] MoveStateNone = 0,
    /// <summary>
    /// 기본상태
    /// </summary>
    [pbr::OriginalName("MOVE_STATE_IDLE")] MoveStateIdle = 1,
    /// <summary>
    /// 달리기
    /// </summary>
    [pbr::OriginalName("MOVE_STATE_RUN")] MoveStateRun = 2,
    /// <summary>
    /// 점프
    /// </summary>
    [pbr::OriginalName("MOVE_STATE_JUMP")] MoveStateJump = 3,
    /// <summary>
    /// 스킬 사용
    /// </summary>
    [pbr::OriginalName("MOVE_STATE_SKILL")] MoveStateSkill = 4,
  }

  public enum EEquipSlotType {
    [pbr::OriginalName("EQUIP_SLOT_TYPE_NONE")] EquipSlotTypeNone = 0,
    /// <summary>
    /// 주무기
    /// </summary>
    [pbr::OriginalName("EQUIP_SLOT_TYPE_WEAPON")] EquipSlotTypeWeapon = 1,
    /// <summary>
    /// 보조무기
    /// </summary>
    [pbr::OriginalName("EQUIP_SLOT_TYPE_SUB_WEAPON")] EquipSlotTypeSubWeapon = 2,
    /// <summary>
    /// 투구
    /// </summary>
    [pbr::OriginalName("EQUIP_SLOT_TYPE_HELMAT")] EquipSlotTypeHelmat = 3,
    /// <summary>
    /// 갑옷
    /// </summary>
    [pbr::OriginalName("EQUIP_SLOT_TYPE_ARMOR")] EquipSlotTypeArmor = 4,
    /// <summary>
    /// 장갑
    /// </summary>
    [pbr::OriginalName("EQUIP_SLOT_TYPE_GLOVES")] EquipSlotTypeGloves = 5,
    /// <summary>
    /// 신발
    /// </summary>
    [pbr::OriginalName("EQUIP_SLOT_TYPE_BOOTS")] EquipSlotTypeBoots = 6,
    [pbr::OriginalName("EQUIP_SLOT_TYPE_MAX")] EquipSlotTypeMax = 7,
  }

  public enum EStat {
    [pbr::OriginalName("STAT_NONE")] StatNone = 0,
    /// <summary>
    /// 힘
    /// </summary>
    [pbr::OriginalName("STAT_STRENGTH")] StatStrength = 1,
    /// <summary>
    /// HP
    /// </summary>
    [pbr::OriginalName("STAT_HP")] StatHp = 2,
    /// <summary>
    /// MP
    /// </summary>
    [pbr::OriginalName("STAT_MP")] StatMp = 3,
    /// <summary>
    /// 방어력
    /// </summary>
    [pbr::OriginalName("STAT_DEFENSE")] StatDefense = 4,
    /// <summary>
    /// 속도
    /// </summary>
    [pbr::OriginalName("STAT_SPEED")] StatSpeed = 5,
    /// <summary>
    /// 지능
    /// </summary>
    [pbr::OriginalName("STAT_INTELLIGENCE")] StatIntelligence = 6,
    [pbr::OriginalName("STAT_MAX")] StatMax = 7,
  }

  public enum EAnimationParamType {
    [pbr::OriginalName("ANIM_PARAM_TYPE_BOOL")] AnimParamTypeBool = 0,
    [pbr::OriginalName("ANIM_PARAM_TYPE_FLOAT")] AnimParamTypeFloat = 1,
    [pbr::OriginalName("ANIM_PARAM_TYPE_TRIGGER")] AnimParamTypeTrigger = 2,
  }

  public enum ERoomState {
    [pbr::OriginalName("ROOM_STATE_NONE")] RoomStateNone = 0,
    /// <summary>
    /// 대기중
    /// </summary>
    [pbr::OriginalName("ROOM_STATE_WAITING")] RoomStateWaiting = 1,
    /// <summary>
    /// 진행중
    /// </summary>
    [pbr::OriginalName("ROOM_STATE_PLAY")] RoomStatePlay = 2,
    [pbr::OriginalName("ROOM_STATE_MAX")] RoomStateMax = 3,
  }

  #endregion

}

#endregion Designer generated code
