// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Enum.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Protocol {

  /// <summary>Holder for reflection information generated from Enum.proto</summary>
  public static partial class EnumReflection {

    #region Descriptor
    /// <summary>File descriptor for Enum.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EnumReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgpFbnVtLnByb3RvEghQcm90b2NvbCqbAQoLRVJlc3VsdENvZGUSFwoTUkVT",
            "VUxUX0NPREVfU1VDQ0VTUxAAEh8KG1JFU1VMVF9DT0RFX0ZBSUxfUk9PTV9F",
            "TlRFUhABEhwKGFJFU1VMVF9DT0RFX05PX0hBVkVfUk9PTRACEh8KG1JFU1VM",
            "VF9DT0RFX05PX1dBSVRJTkdfUk9PTRADEhMKD1JFU1VMVF9DT0RFX01BWBAE",
            "KoABCgtFT2JqZWN0VHlwZRIUChBPQkpFQ1RfVFlQRV9OT05FEAASFQoRT0JK",
            "RUNUX1RZUEVfQUNUT1IQARIaChZPQkpFQ1RfVFlQRV9QUk9KRUNUSUxFEAIS",
            "EwoPT0JKRUNUX1RZUEVfRU5WEAMSEwoPT0JKRUNUX1RZUEVfTUFYEAQqeAoK",
            "RUFjdG9yVHlwZRITCg9BQ1RPUl9UWVBFX05PTkUQABIVChFBQ1RPUl9UWVBF",
            "X1BMQVlFUhABEhYKEkFDVE9SX1RZUEVfTU9OU1RFUhACEhIKDkFDVE9SX1RZ",
            "UEVfTlBDEAMSEgoOQUNUT1JfVFlQRV9NQVgQBCpvCghFQmFnVHlwZRIRCg1C",
            "QUdfVFlQRV9OT05FEAASFgoSQkFHX1RZUEVfRVFVSVBNRU5UEAESEAoMQkFH",
            "X1RZUEVfRVRDEAISFAoQQkFHX1RZUEVfVVNFQUJMRRADEhAKDEJBR19UWVBF",
            "X01BWBAEKn4KC0VQbGF5ZXJUeXBlEhQKEFBMQVlFUl9UWVBFX05PTkUQABIW",
            "ChJQTEFZRVJfVFlQRV9LTklHSFQQARIUChBQTEFZRVJfVFlQRV9NQUdFEAIS",
            "FgoSUExBWUVSX1RZUEVfQVJDSEVSEAMSEwoPUExBWUVSX1RZUEVfTUFYEAQq",
            "dQoKRU1vdmVTdGF0ZRITCg9NT1ZFX1NUQVRFX05PTkUQABITCg9NT1ZFX1NU",
            "QVRFX0lETEUQARISCg5NT1ZFX1NUQVRFX1JVThACEhMKD01PVkVfU1RBVEVf",
            "SlVNUBADEhQKEE1PVkVfU1RBVEVfU0tJTEwQBCrtAQoORUVxdWlwU2xvdFR5",
            "cGUSGAoURVFVSVBfU0xPVF9UWVBFX05PTkUQABIaChZFUVVJUF9TTE9UX1RZ",
            "UEVfV0VBUE9OEAESHgoaRVFVSVBfU0xPVF9UWVBFX1NVQl9XRUFQT04QAhIa",
            "ChZFUVVJUF9TTE9UX1RZUEVfSEVMTUFUEAMSGQoVRVFVSVBfU0xPVF9UWVBF",
            "X0FSTU9SEAQSGgoWRVFVSVBfU0xPVF9UWVBFX0dMT1ZFUxAFEhkKFUVRVUlQ",
            "X1NMT1RfVFlQRV9CT09UUxAGEhcKE0VRVUlQX1NMT1RfVFlQRV9NQVgQByqK",
            "AQoFRVN0YXQSDQoJU1RBVF9OT05FEAASEQoNU1RBVF9TVFJFTkdUSBABEgsK",
            "B1NUQVRfSFAQAhILCgdTVEFUX01QEAMSEAoMU1RBVF9ERUZFTlNFEAQSDgoK",
            "U1RBVF9TUEVFRBAFEhUKEVNUQVRfSU5URUxMSUdFTkNFEAYSDAoIU1RBVF9N",
            "QVgQBypnChNFQW5pbWF0aW9uUGFyYW1UeXBlEhgKFEFOSU1fUEFSQU1fVFlQ",
            "RV9CT09MEAASGQoVQU5JTV9QQVJBTV9UWVBFX0ZMT0FUEAESGwoXQU5JTV9Q",
            "QVJBTV9UWVBFX1RSSUdHRVIQAiqGAQoKRVJvb21TdGF0ZRITCg9ST09NX1NU",
            "QVRFX05PTkUQABIWChJST09NX1NUQVRFX1dBSVRJTkcQARITCg9ST09NX1NU",
            "QVRFX1BMQVkQAhIiCh5ST09NX1NUQVRFX0RFU1RST1lfUkVTRVJWQVRJT04Q",
            "AxISCg5ST09NX1NUQVRFX01BWBAEQguqAghQcm90b2NvbGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Protocol.EResultCode), typeof(global::Protocol.EObjectType), typeof(global::Protocol.EActorType), typeof(global::Protocol.EBagType), typeof(global::Protocol.EPlayerType), typeof(global::Protocol.EMoveState), typeof(global::Protocol.EEquipSlotType), typeof(global::Protocol.EStat), typeof(global::Protocol.EAnimationParamType), typeof(global::Protocol.ERoomState), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum EResultCode {
    /// <summary>
    /// 성공
    /// </summary>
    [pbr::OriginalName("RESULT_CODE_SUCCESS")] ResultCodeSuccess = 0,
    /// <summary>
    /// 룸 입장 실패
    /// </summary>
    [pbr::OriginalName("RESULT_CODE_FAIL_ROOM_ENTER")] ResultCodeFailRoomEnter = 1,
    /// <summary>
    /// 룸이 존재하지않음
    /// </summary>
    [pbr::OriginalName("RESULT_CODE_NO_HAVE_ROOM")] ResultCodeNoHaveRoom = 2,
    /// <summary>
    /// 대기실이 아님
    /// </summary>
    [pbr::OriginalName("RESULT_CODE_NO_WAITING_ROOM")] ResultCodeNoWaitingRoom = 3,
    [pbr::OriginalName("RESULT_CODE_MAX")] ResultCodeMax = 4,
  }

  public enum EObjectType {
    [pbr::OriginalName("OBJECT_TYPE_NONE")] ObjectTypeNone = 0,
    /// <summary>
    /// 엑터
    /// </summary>
    [pbr::OriginalName("OBJECT_TYPE_ACTOR")] ObjectTypeActor = 1,
    /// <summary>
    /// 발사체
    /// </summary>
    [pbr::OriginalName("OBJECT_TYPE_PROJECTILE")] ObjectTypeProjectile = 2,
    /// <summary>
    /// 환경 오브젝트
    /// </summary>
    [pbr::OriginalName("OBJECT_TYPE_ENV")] ObjectTypeEnv = 3,
    [pbr::OriginalName("OBJECT_TYPE_MAX")] ObjectTypeMax = 4,
  }

  public enum EActorType {
    [pbr::OriginalName("ACTOR_TYPE_NONE")] ActorTypeNone = 0,
    /// <summary>
    /// 플레이어
    /// </summary>
    [pbr::OriginalName("ACTOR_TYPE_PLAYER")] ActorTypePlayer = 1,
    /// <summary>
    /// 몬스터
    /// </summary>
    [pbr::OriginalName("ACTOR_TYPE_MONSTER")] ActorTypeMonster = 2,
    /// <summary>
    /// NPC
    /// </summary>
    [pbr::OriginalName("ACTOR_TYPE_NPC")] ActorTypeNpc = 3,
    [pbr::OriginalName("ACTOR_TYPE_MAX")] ActorTypeMax = 4,
  }

  public enum EBagType {
    [pbr::OriginalName("BAG_TYPE_NONE")] BagTypeNone = 0,
    /// <summary>
    /// 장비
    /// </summary>
    [pbr::OriginalName("BAG_TYPE_EQUIPMENT")] BagTypeEquipment = 1,
    /// <summary>
    /// 기타
    /// </summary>
    [pbr::OriginalName("BAG_TYPE_ETC")] BagTypeEtc = 2,
    /// <summary>
    /// 사용품
    /// </summary>
    [pbr::OriginalName("BAG_TYPE_USEABLE")] BagTypeUseable = 3,
    [pbr::OriginalName("BAG_TYPE_MAX")] BagTypeMax = 4,
  }

  public enum EPlayerType {
    [pbr::OriginalName("PLAYER_TYPE_NONE")] PlayerTypeNone = 0,
    /// <summary>
    /// 기사
    /// </summary>
    [pbr::OriginalName("PLAYER_TYPE_KNIGHT")] PlayerTypeKnight = 1,
    /// <summary>
    /// 마법사
    /// </summary>
    [pbr::OriginalName("PLAYER_TYPE_MAGE")] PlayerTypeMage = 2,
    /// <summary>
    /// 궁수
    /// </summary>
    [pbr::OriginalName("PLAYER_TYPE_ARCHER")] PlayerTypeArcher = 3,
    [pbr::OriginalName("PLAYER_TYPE_MAX")] PlayerTypeMax = 4,
  }

  public enum EMoveState {
    [pbr::OriginalName("MOVE_STATE_NONE")] MoveStateNone = 0,
    /// <summary>
    /// 기본상태
    /// </summary>
    [pbr::OriginalName("MOVE_STATE_IDLE")] MoveStateIdle = 1,
    /// <summary>
    /// 달리기
    /// </summary>
    [pbr::OriginalName("MOVE_STATE_RUN")] MoveStateRun = 2,
    /// <summary>
    /// 점프
    /// </summary>
    [pbr::OriginalName("MOVE_STATE_JUMP")] MoveStateJump = 3,
    /// <summary>
    /// 스킬 사용
    /// </summary>
    [pbr::OriginalName("MOVE_STATE_SKILL")] MoveStateSkill = 4,
  }

  public enum EEquipSlotType {
    [pbr::OriginalName("EQUIP_SLOT_TYPE_NONE")] EquipSlotTypeNone = 0,
    /// <summary>
    /// 주무기
    /// </summary>
    [pbr::OriginalName("EQUIP_SLOT_TYPE_WEAPON")] EquipSlotTypeWeapon = 1,
    /// <summary>
    /// 보조무기
    /// </summary>
    [pbr::OriginalName("EQUIP_SLOT_TYPE_SUB_WEAPON")] EquipSlotTypeSubWeapon = 2,
    /// <summary>
    /// 투구
    /// </summary>
    [pbr::OriginalName("EQUIP_SLOT_TYPE_HELMAT")] EquipSlotTypeHelmat = 3,
    /// <summary>
    /// 갑옷
    /// </summary>
    [pbr::OriginalName("EQUIP_SLOT_TYPE_ARMOR")] EquipSlotTypeArmor = 4,
    /// <summary>
    /// 장갑
    /// </summary>
    [pbr::OriginalName("EQUIP_SLOT_TYPE_GLOVES")] EquipSlotTypeGloves = 5,
    /// <summary>
    /// 신발
    /// </summary>
    [pbr::OriginalName("EQUIP_SLOT_TYPE_BOOTS")] EquipSlotTypeBoots = 6,
    [pbr::OriginalName("EQUIP_SLOT_TYPE_MAX")] EquipSlotTypeMax = 7,
  }

  public enum EStat {
    [pbr::OriginalName("STAT_NONE")] StatNone = 0,
    /// <summary>
    /// 힘
    /// </summary>
    [pbr::OriginalName("STAT_STRENGTH")] StatStrength = 1,
    /// <summary>
    /// HP
    /// </summary>
    [pbr::OriginalName("STAT_HP")] StatHp = 2,
    /// <summary>
    /// MP
    /// </summary>
    [pbr::OriginalName("STAT_MP")] StatMp = 3,
    /// <summary>
    /// 방어력
    /// </summary>
    [pbr::OriginalName("STAT_DEFENSE")] StatDefense = 4,
    /// <summary>
    /// 속도
    /// </summary>
    [pbr::OriginalName("STAT_SPEED")] StatSpeed = 5,
    /// <summary>
    /// 지능
    /// </summary>
    [pbr::OriginalName("STAT_INTELLIGENCE")] StatIntelligence = 6,
    [pbr::OriginalName("STAT_MAX")] StatMax = 7,
  }

  public enum EAnimationParamType {
    [pbr::OriginalName("ANIM_PARAM_TYPE_BOOL")] AnimParamTypeBool = 0,
    [pbr::OriginalName("ANIM_PARAM_TYPE_FLOAT")] AnimParamTypeFloat = 1,
    [pbr::OriginalName("ANIM_PARAM_TYPE_TRIGGER")] AnimParamTypeTrigger = 2,
  }

  public enum ERoomState {
    [pbr::OriginalName("ROOM_STATE_NONE")] RoomStateNone = 0,
    /// <summary>
    /// 대기중
    /// </summary>
    [pbr::OriginalName("ROOM_STATE_WAITING")] RoomStateWaiting = 1,
    /// <summary>
    /// 진행중
    /// </summary>
    [pbr::OriginalName("ROOM_STATE_PLAY")] RoomStatePlay = 2,
    /// <summary>
    /// 파괴 예정
    /// </summary>
    [pbr::OriginalName("ROOM_STATE_DESTROY_RESERVATION")] RoomStateDestroyReservation = 3,
    [pbr::OriginalName("ROOM_STATE_MAX")] RoomStateMax = 4,
  }

  #endregion

}

#endregion Designer generated code
