# Server
IP = 127.0.0.1
#IP = 192.168.25.22
PORT = 7777


# DB_common
DB_CONNECT = true
DB_IP = 127.0.0.1
DB_PORT = 3306
DB_NAME = atServer_title
DB_USER = 
DB_PW = 
DB_ASSET_PATH = ../TitleServer/DB/TitleDB.xml