// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Protocol.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_Protocol_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_Protocol_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3017000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3017001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "Enum.pb.h"
#include "Struct.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_Protocol_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_Protocol_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[6]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_Protocol_2eproto;
namespace Protocol {
class CT_EnterLobby;
struct CT_EnterLobbyDefaultTypeInternal;
extern CT_EnterLobbyDefaultTypeInternal _CT_EnterLobby_default_instance_;
class CT_Login;
struct CT_LoginDefaultTypeInternal;
extern CT_LoginDefaultTypeInternal _CT_Login_default_instance_;
class CT_ServerListRead;
struct CT_ServerListReadDefaultTypeInternal;
extern CT_ServerListReadDefaultTypeInternal _CT_ServerListRead_default_instance_;
class ST_EnterLobby;
struct ST_EnterLobbyDefaultTypeInternal;
extern ST_EnterLobbyDefaultTypeInternal _ST_EnterLobby_default_instance_;
class ST_Login;
struct ST_LoginDefaultTypeInternal;
extern ST_LoginDefaultTypeInternal _ST_Login_default_instance_;
class ST_ServerListRead;
struct ST_ServerListReadDefaultTypeInternal;
extern ST_ServerListReadDefaultTypeInternal _ST_ServerListRead_default_instance_;
}  // namespace Protocol
PROTOBUF_NAMESPACE_OPEN
template<> ::Protocol::CT_EnterLobby* Arena::CreateMaybeMessage<::Protocol::CT_EnterLobby>(Arena*);
template<> ::Protocol::CT_Login* Arena::CreateMaybeMessage<::Protocol::CT_Login>(Arena*);
template<> ::Protocol::CT_ServerListRead* Arena::CreateMaybeMessage<::Protocol::CT_ServerListRead>(Arena*);
template<> ::Protocol::ST_EnterLobby* Arena::CreateMaybeMessage<::Protocol::ST_EnterLobby>(Arena*);
template<> ::Protocol::ST_Login* Arena::CreateMaybeMessage<::Protocol::ST_Login>(Arena*);
template<> ::Protocol::ST_ServerListRead* Arena::CreateMaybeMessage<::Protocol::ST_ServerListRead>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace Protocol {

// ===================================================================

class CT_Login final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.CT_Login) */ {
 public:
  inline CT_Login() : CT_Login(nullptr) {}
  ~CT_Login() override;
  explicit constexpr CT_Login(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  CT_Login(const CT_Login& from);
  CT_Login(CT_Login&& from) noexcept
    : CT_Login() {
    *this = ::std::move(from);
  }

  inline CT_Login& operator=(const CT_Login& from) {
    CopyFrom(from);
    return *this;
  }
  inline CT_Login& operator=(CT_Login&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CT_Login& default_instance() {
    return *internal_default_instance();
  }
  static inline const CT_Login* internal_default_instance() {
    return reinterpret_cast<const CT_Login*>(
               &_CT_Login_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(CT_Login& a, CT_Login& b) {
    a.Swap(&b);
  }
  inline void Swap(CT_Login* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CT_Login* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline CT_Login* New() const final {
    return new CT_Login();
  }

  CT_Login* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<CT_Login>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const CT_Login& from);
  void MergeFrom(const CT_Login& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CT_Login* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.CT_Login";
  }
  protected:
  explicit CT_Login(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kIdFieldNumber = 1,
    kPwFieldNumber = 2,
  };
  // string id = 1;
  void clear_id();
  const std::string& id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_id();
  PROTOBUF_FUTURE_MUST_USE_RESULT std::string* release_id();
  void set_allocated_id(std::string* id);
  private:
  const std::string& _internal_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_id(const std::string& value);
  std::string* _internal_mutable_id();
  public:

  // int32 pw = 2;
  void clear_pw();
  ::PROTOBUF_NAMESPACE_ID::int32 pw() const;
  void set_pw(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_pw() const;
  void _internal_set_pw(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.CT_Login)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr id_;
  ::PROTOBUF_NAMESPACE_ID::int32 pw_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_Protocol_2eproto;
};
// -------------------------------------------------------------------

class ST_Login final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.ST_Login) */ {
 public:
  inline ST_Login() : ST_Login(nullptr) {}
  ~ST_Login() override;
  explicit constexpr ST_Login(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ST_Login(const ST_Login& from);
  ST_Login(ST_Login&& from) noexcept
    : ST_Login() {
    *this = ::std::move(from);
  }

  inline ST_Login& operator=(const ST_Login& from) {
    CopyFrom(from);
    return *this;
  }
  inline ST_Login& operator=(ST_Login&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ST_Login& default_instance() {
    return *internal_default_instance();
  }
  static inline const ST_Login* internal_default_instance() {
    return reinterpret_cast<const ST_Login*>(
               &_ST_Login_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(ST_Login& a, ST_Login& b) {
    a.Swap(&b);
  }
  inline void Swap(ST_Login* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ST_Login* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ST_Login* New() const final {
    return new ST_Login();
  }

  ST_Login* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ST_Login>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ST_Login& from);
  void MergeFrom(const ST_Login& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ST_Login* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.ST_Login";
  }
  protected:
  explicit ST_Login(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSuccessFieldNumber = 1,
  };
  // bool success = 1;
  void clear_success();
  bool success() const;
  void set_success(bool value);
  private:
  bool _internal_success() const;
  void _internal_set_success(bool value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.ST_Login)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  bool success_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_Protocol_2eproto;
};
// -------------------------------------------------------------------

class CT_EnterLobby final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.CT_EnterLobby) */ {
 public:
  inline CT_EnterLobby() : CT_EnterLobby(nullptr) {}
  ~CT_EnterLobby() override;
  explicit constexpr CT_EnterLobby(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  CT_EnterLobby(const CT_EnterLobby& from);
  CT_EnterLobby(CT_EnterLobby&& from) noexcept
    : CT_EnterLobby() {
    *this = ::std::move(from);
  }

  inline CT_EnterLobby& operator=(const CT_EnterLobby& from) {
    CopyFrom(from);
    return *this;
  }
  inline CT_EnterLobby& operator=(CT_EnterLobby&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CT_EnterLobby& default_instance() {
    return *internal_default_instance();
  }
  static inline const CT_EnterLobby* internal_default_instance() {
    return reinterpret_cast<const CT_EnterLobby*>(
               &_CT_EnterLobby_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(CT_EnterLobby& a, CT_EnterLobby& b) {
    a.Swap(&b);
  }
  inline void Swap(CT_EnterLobby* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CT_EnterLobby* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline CT_EnterLobby* New() const final {
    return new CT_EnterLobby();
  }

  CT_EnterLobby* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<CT_EnterLobby>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const CT_EnterLobby& from);
  void MergeFrom(const CT_EnterLobby& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CT_EnterLobby* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.CT_EnterLobby";
  }
  protected:
  explicit CT_EnterLobby(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:Protocol.CT_EnterLobby)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_Protocol_2eproto;
};
// -------------------------------------------------------------------

class ST_EnterLobby final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.ST_EnterLobby) */ {
 public:
  inline ST_EnterLobby() : ST_EnterLobby(nullptr) {}
  ~ST_EnterLobby() override;
  explicit constexpr ST_EnterLobby(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ST_EnterLobby(const ST_EnterLobby& from);
  ST_EnterLobby(ST_EnterLobby&& from) noexcept
    : ST_EnterLobby() {
    *this = ::std::move(from);
  }

  inline ST_EnterLobby& operator=(const ST_EnterLobby& from) {
    CopyFrom(from);
    return *this;
  }
  inline ST_EnterLobby& operator=(ST_EnterLobby&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ST_EnterLobby& default_instance() {
    return *internal_default_instance();
  }
  static inline const ST_EnterLobby* internal_default_instance() {
    return reinterpret_cast<const ST_EnterLobby*>(
               &_ST_EnterLobby_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(ST_EnterLobby& a, ST_EnterLobby& b) {
    a.Swap(&b);
  }
  inline void Swap(ST_EnterLobby* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ST_EnterLobby* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ST_EnterLobby* New() const final {
    return new ST_EnterLobby();
  }

  ST_EnterLobby* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ST_EnterLobby>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ST_EnterLobby& from);
  void MergeFrom(const ST_EnterLobby& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ST_EnterLobby* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.ST_EnterLobby";
  }
  protected:
  explicit ST_EnterLobby(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPlayerIdFieldNumber = 2,
    kSuccessFieldNumber = 1,
  };
  // uint64 playerId = 2;
  void clear_playerid();
  ::PROTOBUF_NAMESPACE_ID::uint64 playerid() const;
  void set_playerid(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_playerid() const;
  void _internal_set_playerid(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // bool success = 1;
  void clear_success();
  bool success() const;
  void set_success(bool value);
  private:
  bool _internal_success() const;
  void _internal_set_success(bool value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.ST_EnterLobby)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::uint64 playerid_;
  bool success_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_Protocol_2eproto;
};
// -------------------------------------------------------------------

class CT_ServerListRead final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.CT_ServerListRead) */ {
 public:
  inline CT_ServerListRead() : CT_ServerListRead(nullptr) {}
  ~CT_ServerListRead() override;
  explicit constexpr CT_ServerListRead(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  CT_ServerListRead(const CT_ServerListRead& from);
  CT_ServerListRead(CT_ServerListRead&& from) noexcept
    : CT_ServerListRead() {
    *this = ::std::move(from);
  }

  inline CT_ServerListRead& operator=(const CT_ServerListRead& from) {
    CopyFrom(from);
    return *this;
  }
  inline CT_ServerListRead& operator=(CT_ServerListRead&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CT_ServerListRead& default_instance() {
    return *internal_default_instance();
  }
  static inline const CT_ServerListRead* internal_default_instance() {
    return reinterpret_cast<const CT_ServerListRead*>(
               &_CT_ServerListRead_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(CT_ServerListRead& a, CT_ServerListRead& b) {
    a.Swap(&b);
  }
  inline void Swap(CT_ServerListRead* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CT_ServerListRead* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline CT_ServerListRead* New() const final {
    return new CT_ServerListRead();
  }

  CT_ServerListRead* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<CT_ServerListRead>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const CT_ServerListRead& from);
  void MergeFrom(const CT_ServerListRead& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CT_ServerListRead* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.CT_ServerListRead";
  }
  protected:
  explicit CT_ServerListRead(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:Protocol.CT_ServerListRead)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_Protocol_2eproto;
};
// -------------------------------------------------------------------

class ST_ServerListRead final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.ST_ServerListRead) */ {
 public:
  inline ST_ServerListRead() : ST_ServerListRead(nullptr) {}
  ~ST_ServerListRead() override;
  explicit constexpr ST_ServerListRead(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ST_ServerListRead(const ST_ServerListRead& from);
  ST_ServerListRead(ST_ServerListRead&& from) noexcept
    : ST_ServerListRead() {
    *this = ::std::move(from);
  }

  inline ST_ServerListRead& operator=(const ST_ServerListRead& from) {
    CopyFrom(from);
    return *this;
  }
  inline ST_ServerListRead& operator=(ST_ServerListRead&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ST_ServerListRead& default_instance() {
    return *internal_default_instance();
  }
  static inline const ST_ServerListRead* internal_default_instance() {
    return reinterpret_cast<const ST_ServerListRead*>(
               &_ST_ServerListRead_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(ST_ServerListRead& a, ST_ServerListRead& b) {
    a.Swap(&b);
  }
  inline void Swap(ST_ServerListRead* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ST_ServerListRead* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ST_ServerListRead* New() const final {
    return new ST_ServerListRead();
  }

  ST_ServerListRead* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ST_ServerListRead>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ST_ServerListRead& from);
  void MergeFrom(const ST_ServerListRead& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ST_ServerListRead* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.ST_ServerListRead";
  }
  protected:
  explicit ST_ServerListRead(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kServerInfoListFieldNumber = 2,
    kResultFieldNumber = 1,
  };
  // repeated .Protocol.ServerInfo serverInfoList = 2;
  int serverinfolist_size() const;
  private:
  int _internal_serverinfolist_size() const;
  public:
  void clear_serverinfolist();
  ::Protocol::ServerInfo* mutable_serverinfolist(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::ServerInfo >*
      mutable_serverinfolist();
  private:
  const ::Protocol::ServerInfo& _internal_serverinfolist(int index) const;
  ::Protocol::ServerInfo* _internal_add_serverinfolist();
  public:
  const ::Protocol::ServerInfo& serverinfolist(int index) const;
  ::Protocol::ServerInfo* add_serverinfolist();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::ServerInfo >&
      serverinfolist() const;

  // .Protocol.EResultCode result = 1;
  void clear_result();
  ::Protocol::EResultCode result() const;
  void set_result(::Protocol::EResultCode value);
  private:
  ::Protocol::EResultCode _internal_result() const;
  void _internal_set_result(::Protocol::EResultCode value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.ST_ServerListRead)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::ServerInfo > serverinfolist_;
  int result_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_Protocol_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// CT_Login

// string id = 1;
inline void CT_Login::clear_id() {
  id_.ClearToEmpty();
}
inline const std::string& CT_Login::id() const {
  // @@protoc_insertion_point(field_get:Protocol.CT_Login.id)
  return _internal_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void CT_Login::set_id(ArgT0&& arg0, ArgT... args) {
 
 id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Protocol.CT_Login.id)
}
inline std::string* CT_Login::mutable_id() {
  // @@protoc_insertion_point(field_mutable:Protocol.CT_Login.id)
  return _internal_mutable_id();
}
inline const std::string& CT_Login::_internal_id() const {
  return id_.Get();
}
inline void CT_Login::_internal_set_id(const std::string& value) {
  
  id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* CT_Login::_internal_mutable_id() {
  
  return id_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* CT_Login::release_id() {
  // @@protoc_insertion_point(field_release:Protocol.CT_Login.id)
  return id_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void CT_Login::set_allocated_id(std::string* id) {
  if (id != nullptr) {
    
  } else {
    
  }
  id_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), id,
      GetArenaForAllocation());
  // @@protoc_insertion_point(field_set_allocated:Protocol.CT_Login.id)
}

// int32 pw = 2;
inline void CT_Login::clear_pw() {
  pw_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 CT_Login::_internal_pw() const {
  return pw_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 CT_Login::pw() const {
  // @@protoc_insertion_point(field_get:Protocol.CT_Login.pw)
  return _internal_pw();
}
inline void CT_Login::_internal_set_pw(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  pw_ = value;
}
inline void CT_Login::set_pw(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_pw(value);
  // @@protoc_insertion_point(field_set:Protocol.CT_Login.pw)
}

// -------------------------------------------------------------------

// ST_Login

// bool success = 1;
inline void ST_Login::clear_success() {
  success_ = false;
}
inline bool ST_Login::_internal_success() const {
  return success_;
}
inline bool ST_Login::success() const {
  // @@protoc_insertion_point(field_get:Protocol.ST_Login.success)
  return _internal_success();
}
inline void ST_Login::_internal_set_success(bool value) {
  
  success_ = value;
}
inline void ST_Login::set_success(bool value) {
  _internal_set_success(value);
  // @@protoc_insertion_point(field_set:Protocol.ST_Login.success)
}

// -------------------------------------------------------------------

// CT_EnterLobby

// -------------------------------------------------------------------

// ST_EnterLobby

// bool success = 1;
inline void ST_EnterLobby::clear_success() {
  success_ = false;
}
inline bool ST_EnterLobby::_internal_success() const {
  return success_;
}
inline bool ST_EnterLobby::success() const {
  // @@protoc_insertion_point(field_get:Protocol.ST_EnterLobby.success)
  return _internal_success();
}
inline void ST_EnterLobby::_internal_set_success(bool value) {
  
  success_ = value;
}
inline void ST_EnterLobby::set_success(bool value) {
  _internal_set_success(value);
  // @@protoc_insertion_point(field_set:Protocol.ST_EnterLobby.success)
}

// uint64 playerId = 2;
inline void ST_EnterLobby::clear_playerid() {
  playerid_ = uint64_t{0u};
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 ST_EnterLobby::_internal_playerid() const {
  return playerid_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 ST_EnterLobby::playerid() const {
  // @@protoc_insertion_point(field_get:Protocol.ST_EnterLobby.playerId)
  return _internal_playerid();
}
inline void ST_EnterLobby::_internal_set_playerid(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  playerid_ = value;
}
inline void ST_EnterLobby::set_playerid(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_playerid(value);
  // @@protoc_insertion_point(field_set:Protocol.ST_EnterLobby.playerId)
}

// -------------------------------------------------------------------

// CT_ServerListRead

// -------------------------------------------------------------------

// ST_ServerListRead

// .Protocol.EResultCode result = 1;
inline void ST_ServerListRead::clear_result() {
  result_ = 0;
}
inline ::Protocol::EResultCode ST_ServerListRead::_internal_result() const {
  return static_cast< ::Protocol::EResultCode >(result_);
}
inline ::Protocol::EResultCode ST_ServerListRead::result() const {
  // @@protoc_insertion_point(field_get:Protocol.ST_ServerListRead.result)
  return _internal_result();
}
inline void ST_ServerListRead::_internal_set_result(::Protocol::EResultCode value) {
  
  result_ = value;
}
inline void ST_ServerListRead::set_result(::Protocol::EResultCode value) {
  _internal_set_result(value);
  // @@protoc_insertion_point(field_set:Protocol.ST_ServerListRead.result)
}

// repeated .Protocol.ServerInfo serverInfoList = 2;
inline int ST_ServerListRead::_internal_serverinfolist_size() const {
  return serverinfolist_.size();
}
inline int ST_ServerListRead::serverinfolist_size() const {
  return _internal_serverinfolist_size();
}
inline ::Protocol::ServerInfo* ST_ServerListRead::mutable_serverinfolist(int index) {
  // @@protoc_insertion_point(field_mutable:Protocol.ST_ServerListRead.serverInfoList)
  return serverinfolist_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::ServerInfo >*
ST_ServerListRead::mutable_serverinfolist() {
  // @@protoc_insertion_point(field_mutable_list:Protocol.ST_ServerListRead.serverInfoList)
  return &serverinfolist_;
}
inline const ::Protocol::ServerInfo& ST_ServerListRead::_internal_serverinfolist(int index) const {
  return serverinfolist_.Get(index);
}
inline const ::Protocol::ServerInfo& ST_ServerListRead::serverinfolist(int index) const {
  // @@protoc_insertion_point(field_get:Protocol.ST_ServerListRead.serverInfoList)
  return _internal_serverinfolist(index);
}
inline ::Protocol::ServerInfo* ST_ServerListRead::_internal_add_serverinfolist() {
  return serverinfolist_.Add();
}
inline ::Protocol::ServerInfo* ST_ServerListRead::add_serverinfolist() {
  // @@protoc_insertion_point(field_add:Protocol.ST_ServerListRead.serverInfoList)
  return _internal_add_serverinfolist();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::ServerInfo >&
ST_ServerListRead::serverinfolist() const {
  // @@protoc_insertion_point(field_list:Protocol.ST_ServerListRead.serverInfoList)
  return serverinfolist_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace Protocol

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_Protocol_2eproto
